Upgrade to rm-0.5.0
App startup log:
Starting up the mesh.
Starting RightMesh Java version: 0.5.0-RELEASE
Enter messages to send to all other peers
Exception in thread "Thread-26" java.lang.NoClassDefFoundError: org/json/JSONObject
        at io.left.rightmesh.mesh.TransactionManager.a(SourceFile:832)
        at io.left.rightmesh.mesh.TransactionManager.k(SourceFile:1059)
        at io.left.rightmesh.mesh.TransactionManager.tryToInitChannels(SourceFile:1595)
        at io.left.rightmesh.mesh.h.e(SourceFile:552)
        at io.left.rightmesh.proto.a.e(SourceFile:410)
        at io.left.rightmesh.proto.a.b(SourceFile:2243)
        at io.left.rightmesh.proto.a$4.run(SourceFile:170)
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more