Upgrade to rm-0.4.4
App startup log
Starting RightMesh Java version: 0.4.4-RELEASE
Enter messages to send to all other peers
Exception in thread "Thread-24" java.lang.NoClassDefFoundError: org/json/JSONObject
        at io.left.rightmesh.mesh.TransactionManager.c(SourceFile:766)
        at io.left.rightmesh.mesh.TransactionManager.e(SourceFile:834)
        at io.left.rightmesh.mesh.TransactionManager.tryToInitChannels(SourceFile:1116)
        at io.left.rightmesh.mesh.f.c(SourceFile:525)
        at io.left.rightmesh.proto.e.b(SourceFile:410)
        at io.left.rightmesh.proto.e.e(SourceFile:2244)
        at io.left.rightmesh.proto.e$1.run(SourceFile:171)
Caused by: java.lang.ClassNotFoundException: org.json.JSONObject
        at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 7 more